### PR TITLE
Feature One  ( Main Page  ) 

### PR DESCRIPTION
**Pull request by HtetWaiYan7191**
### This Pull Request includes the following changes : 

- Get Data from the [themealdbAPI](https://www.themealdb.com/api.php)
- Display cards using the data from the API  
- [Involvement](https://microverse.notion.site/Involvement-API-869e60b5ad104603aa6db59e08150270) Use involvement API to add reaction 
- Add all the meal cards by using Javascript 
- Build structure the main page 
- Implement style for main page 

Thank you very much for reviewing my code 😀

### CODE REVIEW

**Comment by aamir-asaram** [comment]
## STATUS: CHANGES REQUIRED :recycle: 
giphy

Hey @HtetWaiYan7191, you've done an amazing job implementing the required functionality of the application! 
**Highlights**
- Very clean, readable code
- Stunning design based on the wireframe
- Working API calls

### Suggested Changes
- [ ] Your current application allows users to like a meal more than once. Kindly consider adding a condition to prevent this. Something along the lines of `!e.target.classList.contains('fa-solid')` should do the trick :smile:
- [ ] You also currently regenerate an API key for the Involvement API each time your page is refreshed. As a result of this, your likes are not properly stored and are reset to 0 whenever the page is refreshed. Consider just adding one API key to your program and removing the function to generate new keys.

**[Optional]**
meal

- [ ] Kindly consider changing the circled text to match the font size and colour of the rest of the text as it currently sticks out noticeably.
- [ ] Also consider increasing the font size of the nav-bar headings - this will improve the visibility and overall UX of your page.

Feel free to message me if anything is unclear. Cheers and happy coding :smile:

**Comment by aamir-asaram** [comment]
## STATUS: APPROVED :fire: 
goodjob

Congratulations, your project is complete! There's nothing left to say other than... it's time to merge. :clap: :clap:

**Comment by HtetWaiYan7191** [comment]
Thank you very much for reviewing my code @aamir-asaram

**Review by aamir-asaram — APPROVED** [review]
## STATUS: APPROVED :+1:
goodjob
Hey @HtetWaiYan7191, 
Congratulations, your project is complete! There is nothing left to say other than... it's time to merge it. :clap::clap::clap:

**Pull request merged**
